# Generated by Django 4.1.4 on 2023-02-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addportfoilio',
            old_name='post_desc',
            new_name='project_desc',
        ),
        migrations.RenameField(
            model_name='addportfoilio',
            old_name='post_name',
            new_name='project_name',
        ),
    ]
