# Generated by Django 4.1.4 on 2023-02-09 15:53

from django.db import migrations, models
import django.utils.timezone
import portfolioApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_rename_post_desc_addportfoilio_project_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addportfoilio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolioApp.models.filepath),
        ),
        migrations.AddField(
            model_name='addportfoilio',
            name='project_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addportfoilio',
            name='project_desc',
            field=models.TextField(max_length=2000),
        ),
    ]
