# Generated by Django 4.1.4 on 2023-02-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_addportfoilio_image_addportfoilio_project_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addPortfoilio',
            new_name='myproject',
        ),
    ]
