# Generated by Django 4.1.4 on 2023-02-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_rename_addportfoilio_myproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_greeting', models.CharField(max_length=200)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_intro', models.TextField(max_length=1000)),
                ('hero_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='projectcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_completed', models.IntegerField(max_length=1000)),
                ('web_application', models.IntegerField(max_length=1000)),
                ('mobile_application', models.IntegerField(max_length=1000)),
                ('uiux_design', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
