# Generated by Django 4.1.4 on 2023-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_copyright_herosection_projectcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_link', models.CharField(max_length=1000)),
                ('service_title', models.CharField(max_length=500)),
                ('service_dec', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='copyright',
            name='copyright',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectcount',
            name='mobile_application',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectcount',
            name='project_completed',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectcount',
            name='uiux_design',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectcount',
            name='web_application',
            field=models.CharField(max_length=1000),
        ),
    ]
