# Generated by Django 4.1.4 on 2023-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_rename_icon_link_serviceoffer_iconname'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=100)),
                ('skills_in_percent', models.IntegerField()),
            ],
        ),
    ]
