# Generated by Django 4.1.4 on 2023-02-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='image_link',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
