# Generated by Django 4.1.4 on 2023-02-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0009_myproject_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='hero_img',
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_img_link',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
