# Generated by Django 4.1.4 on 2023-02-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_remove_herosection_hero_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='image',
        ),
    ]
