# Generated by Django 4.1.4 on 2023-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0011_remove_myproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='maplocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_location', models.CharField(max_length=500)),
                ('location_map_api_link', models.TextField(max_length=5000)),
            ],
        ),
    ]
