# Generated by Django 4.1.4 on 2023-02-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0012_maplocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcount',
            old_name='mobile_application',
            new_name='countdown',
        ),
        migrations.RenameField(
            model_name='projectcount',
            old_name='project_completed',
            new_name='countdown_title',
        ),
        migrations.RemoveField(
            model_name='projectcount',
            name='uiux_design',
        ),
        migrations.RemoveField(
            model_name='projectcount',
            name='web_application',
        ),
    ]
