# Generated by Django 4.1.7 on 2023-03-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0014_learing_resource_socialmedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learing_resource',
            name='img_link',
        ),
    ]
