# Generated by Django 4.1.7 on 2023-03-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0015_remove_learing_resource_img_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffer',
            name='service_dec',
        ),
    ]
